server.port: 8081
server.servlet.context-path=/newsScraper
spring.threads.virtual.enabled=true
spring.main.keep-alive=true

solr.server.articles.url: http://localhost:8983/solr/articles
#solr.server.articles.url: http://192.168.0.100:8983/solr/articles
    
#LogBack Configuration
logging.config = classpath:logback.xml
logging.file = myLogs.log
logging.register-shutdown-hook = true